#!/usr/bin/env python3
# Filename: problem_2.py
"""
Problem 2
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import time

def problem_2():
    ans = 0
    fib = [1,1,2]
    while fib[-1] < 4_000_000:
        if fib[-1] % 2 == 0:
            ans += fib[-1]
        fib = fib[1:]
        fib.append(sum(fib))

    return ans 

if __name__ == "__main__":
    start_time = time.time()
    result = problem_2()
    end_time = time.time()

    print(f"The answer is {result:,}.")
    print(f"The the solution took {end_time-start_time:0.2} seconds.")
